import streamlit as st
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

from src.data_loader import load_kaggle_fraud_data, inject_label_noise
from src.evaluator import run_evaluation_loop, compute_statistical_significance

# ==========================================
# PAGE CONFIGURATION
# ==========================================
st.set_page_config(page_title="AL-Clean Dashboard", layout="wide", page_icon="🛡️")

st.title("🛡️ AL-Clean: Confident Active Learning Dashboard")
st.markdown("Interactive benchmark of Uncertainty-Aware Active Learning & Confident Learning under label noise.")

# ==========================================
# SIDEBAR CONTROLS
# ==========================================
st.sidebar.header("⚙️ Configuration Panel")
noise_level = st.sidebar.slider("Label Noise Level (%)", min_value=0, max_value=50, value=15, step=1) / 100.0
al_step_size = st.sidebar.number_input("AL Query Step Size", min_value=100, max_value=2000, value=500, step=100)

st.sidebar.markdown("---")
st.sidebar.markdown("### Execution Note")
st.sidebar.markdown("For interactive speed, this dashboard will subsample 15,000 records from the Kaggle Dataset natively while maintaining class distribution.")

# ==========================================
# DASHBOARD LOGIC
# ==========================================
if st.sidebar.button("▶️ Run Pipeline Engine"):
    
    # Placeholders for live console logs
    log_area = st.empty()
    
    with st.spinner("Fetching dataset, optimizing XGBoost, and running the Active Learning loops..."):
        
        # 1. Load Data (subsampled for speed in app)
        X, y_true = load_kaggle_fraud_data(csv_path="creditcard.csv", subsample=15000)
        y_noisy = inject_label_noise(y_true, noise_level=noise_level)
        
        # 2. Run Evaluator Pipelines
        clean_pr, clean_mcc, total_pruned = run_evaluation_loop(
            X, y_noisy, y_true, use_cleanlab=True, al_step_size=al_step_size
        )
        
        std_pr, std_mcc, _ = run_evaluation_loop(
            X, y_noisy, y_true, use_cleanlab=False, al_step_size=al_step_size
        )
        
    st.success("✅ Modular Pipeline Execution Complete!")
    st.markdown("---")
    
    # ==========================================
    # METRICS & STATISTICAL SIGNIFICANCE
    # ==========================================
    col1, col2 = st.columns(2)
    
    # Card 1: Pruned Count
    with col1:
        st.metric(
            label="Total Corrupted Labels Pruned 🧹", 
            value=f"{total_pruned} samples",
            help="Total number of false labels accurately identified and removed by Cleanlab before entering the training pool."
        )
        
    # Card 2: Significance
    p_value = compute_statistical_significance(std_pr, clean_pr)
    if p_value < 0.05:
        interpretation = "Statistically Significant ✅ (p < 0.05)"
        delta_color = "normal"
    else:
        interpretation = "Not Significant ❌"
        delta_color = "inverse"
        
    with col2:
        st.metric(
            label="Wilcoxon Signed-Rank Test (PR-AUC) 📉", 
            value=f"{p_value:.4f}", 
            delta=interpretation, 
            delta_color=delta_color,
            help="Computes if the performance lift generated by AL-Clean is statistically significant compared to the baseline AL pipeline."
        )
        
    st.markdown("---")
    
    # ==========================================
    # CHART VISUALIZATIONS
    # ==========================================
    iterations = np.arange(1, 6)
    
    # Combine Data for plotting
    df_pr = pd.DataFrame({
        "Iteration": iterations,
        "AL-Clean (With Cleanlab)": clean_pr,
        "Standard AL (No Cleanlab)": std_pr
    }).set_index("Iteration")
    
    df_mcc = pd.DataFrame({
        "Iteration": iterations,
        "AL-Clean (With Cleanlab)": clean_mcc,
        "Standard AL (No Cleanlab)": std_mcc
    }).set_index("Iteration")
    
    chart_col1, chart_col2 = st.columns(2)
    
    with chart_col1:
        st.subheader("📈 Precision-Recall AUC Comparison")
        st.line_chart(df_pr)
        
    with chart_col2:
        st.subheader("📊 Matthews Correlation Coefficient (MCC)")
        st.line_chart(df_mcc)
        
else:
    # Idle State
    st.info("👈 Please adjust your parameters in the Configuration Panel and click **Run Pipeline Engine** to start.")
